### ISSUE TITLE
Crash when opening morph menu

### ISSUE THREAD

**Issue by SimonsBrother** [ToCraft/Remorphed#54]
### Mod loader

Forge

### Minecraft version

1.20.1

### Remorphed version

4.2

### Woodwalkers version

5.5

### CraftedCore version

5.7

### Modloader version

47.3.12

### The latest.log file

The log is too big to paste in, I uploaded it to wetransfer before I made a Gist-file. I hope it's suitable, if not, just let me know.
https://we.tl/t-0usQVwxDOY

### Issue description

Game crashes when I press the key "Open menu to choose second shape".

### Steps to reproduce

1. Start game
2. Create new world
3. Press the key assigned for "Open menu to choose second shape"
4. Game crashes without showing menu

### Other

The crash log suspected Blueprint and GeckoLib as well, might be an incompatibility? See part of the crash log below:

Suspected Mods: 
	Blueprint (blueprint), Version: 7.1.0
		Issue tracker URL: https://github.com/team-abnormals/blueprint/issues
		at TRANSFORMER/blueprint@7.1.0/com.teamabnormals.blueprint.common.remolder.RemoldedResourceManager.getResourceFunction(RemoldedResourceManager.java:154)

	CraftedCore (craftedcore), Version: 5.7
		Issue tracker URL: https://github.com/ToCraft/craftedcore/issues
		at TRANSFORMER/craftedcore@5.7/tocraft.craftedcore.patched.client.CGraphics.blit(CGraphics.java:52)

	GeckoLib 4 (geckolib), Version: 4.4.9
		Issue tracker URL: https://github.com/bernie-g/geckolib/issues
		at TRANSFORMER/geckolib@4.4.9/software.bernie.geckolib.cache.texture.AnimatableTexture.m_6704_(AnimatableTexture.java:40)

	ReMorphed (remorphed), Version: 4.2
		Issue tracker URL: https://github.com/ToCraft/Remorphed/issues
		at TRANSFORMER/remorphed@4.2/tocraft.remorphed.screen.widget.PlayerWidget.m_8

**Comment by SimonsBrother** [comment]
I just tested this on MacOS - no problems. Only seems to be an issue on Windows.

**Comment by ToCraft** [comment]
Hey! I just wanted to take a look at your log, but I can't download it since WeTransfer already deleted it. Could you upload it again on [GitHub Gist](https://github.com/gist) or [mclo.gs](https://mclo.gs)?

**Comment by SimonsBrother** [comment]
Hi, I've also lost the original latest.log that I sent, but here's another: https://mclo.gs/LghPoQN
Thanks for taking a look!

**Comment by ToCraft** [comment]
Alright. It's most likely a coding error in Mowzie's Mobs. You can look for an entity called similar to LegSolver or LegSolverQuadruped. If you try to summon it with `/summon`, it should output an error. You should report it to them instead. Until they answer, you can [blacklist](https://github.com/ToCraft/woodwalkers-mod/wiki/Configuration#entityblacklist) it in the `config/walkers.json5` file in the `entityBlacklist`.

<details>
<summary>excerpt from your log containing the error <i>(Click to expand)</i></summary>

```log
	[01Jan2025 21:53:21.001] [ForkJoinPool.commonPool-worker-8/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: Could not find parent com/bobmowzie/mowziesmobs/server/entity/LegSolver for class com/bobmowzie/mowziesmobs/server/entity/LegSolverQuadruped in classloader jdk.internal.loader.ClassLoaders$AppClassLoader@6442b0a6 on thread Thread[ForkJoinPool.commonPool-worker-8,4,SERVER]
[01Jan2025 21:53:21.001] [ForkJoinPool.commonPool-worker-8/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.ClassNotFoundException: com.bobmowzie.mowziesmobs.server.entity.LegSolver
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:97) ~[eventbus-6.0.5.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:48) ~[eventbus-6.0.5.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.5.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.5.jar:6.0.5+6.0.5+master.eb8e549b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at com.bobmowzie.mowziesmobs.server.entity.frostmaw.EntityFrostmaw.<init>(EntityFrostmaw.java:117) ~[?:?]
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525) ~[?:?]
	at tocraft.walkers.api.variant.ShapeType.getAllTypes(ShapeType.java:119) ~[?:?]
	at tocraft.remorphed.Remorphed.getUnlockedShapes(Remorphed.java:83) ~[?:?]
	at tocraft.remorphed.screen.RemorphedScreen.populateUnlockedRenderEntities(RemorphedScreen.java:322) ~[?:?]
	at tocraft.remorphed.screen.RemorphedScreen.instantiate(RemorphedScreen.java:89) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

</details>
